version: '3'

services:

  postgresdb:
   image: postgres
   container_name: postgresdb
   ports:
    - "5444:5432"
   environment:
    - POSTGRES_USER=root
    - POSTGRES_DB=ask_db
    - POSTGRES_PASSWORD=root
   networks: ['stack']

  redisdb:
    image: redis:5.0.0
    container_name: redisdb
    ports:
      - "6372:6379"
    networks: ['stack']

  ask_app:
   image: ask_app:latest
   build:
     context: .
     dockerfile: ./docker/Dockerfile
   container_name: ask_app
   volumes:
     - .:/app
   ports:
     - "7000:8000"
   depends_on:
     - postgresdb
   environment:
     - STAGE=dev
   networks: ['stack']
   command: /start




networks:
  stack:
    driver: bridge